INSERT INTO users (email, username, password, avatar_path)
VALUES 
('user1@example.com', 'user1', '123', 'assets/images/user/avatar1.png'),
('user2@example.com', 'user2', '123', 'assets/images/user/avatar1.png'),
('user3@example.com', 'user3', '123', 'assets/images/user/avatar1.png'),
('user4@example.com', 'user4', '123', 'assets/images/user/avatar1.png'),
('user5@example.com', 'user5', '123', 'assets/images/user/avatar1.png'),
('user6@example.com', 'user6', '123', 'assets/images/user/avatar1.png'),
('user7@example.com', 'user7', '123', 'assets/images/user/avatar1.png'),
('user8@example.com', 'user8', '123', 'assets/images/user/avatar1.png'),
('user9@example.com', 'user9', '123', 'assets/images/user/avatar1.png'),
('user10@example.com', 'user10', '123', 'assets/images/user/avatar1.png'),
('user11@example.com', 'user11', '123', 'assets/images/user/avatar1.png'),
('user12@example.com', 'user12', '123', 'assets/images/user/avatar1.png'),
('user13@example.com', 'user13', '123', 'assets/images/user/avatar1.png'),
('user14@example.com', 'user14', '123', 'assets/images/user/avatar1.png'),
('user15@example.com', 'user15', '123', 'assets/images/user/avatar1.png'),
('user16@example.com', 'user16', '123', 'assets/images/user/avatar1.png'),
('user17@example.com', 'user17', '123', 'assets/images/user/avatar1.png'),
('user18@example.com', 'user18', '123', 'assets/images/user/avatar1.png'),
('user19@example.com', 'user19', '123', 'assets/images/user/avatar1.png'),
('user20@example.com', 'user20', '123', 'assets/images/user/avatar1.png');